# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/camilo/cmake/integration

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/camilo/cmake/integration

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/camilo/cmake/integration && $(CMAKE_COMMAND) -E cmake_progress_start /home/camilo/cmake/integration/CMakeFiles /home/camilo/cmake/integration/port/base/unac//CMakeFiles/progress.marks
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port/base/unac/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/camilo/cmake/integration/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port/base/unac/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port/base/unac/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port/base/unac/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/camilo/cmake/integration && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
port/base/unac/CMakeFiles/unac.dir/rule:
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port/base/unac/CMakeFiles/unac.dir/rule
.PHONY : port/base/unac/CMakeFiles/unac.dir/rule

# Convenience name for target.
unac: port/base/unac/CMakeFiles/unac.dir/rule
.PHONY : unac

# fast build rule for target.
unac/fast:
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f port/base/unac/CMakeFiles/unac.dir/build.make port/base/unac/CMakeFiles/unac.dir/build
.PHONY : unac/fast

# Convenience name for target.
port/base/unac/CMakeFiles/static_unac.dir/rule:
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 port/base/unac/CMakeFiles/static_unac.dir/rule
.PHONY : port/base/unac/CMakeFiles/static_unac.dir/rule

# Convenience name for target.
static_unac: port/base/unac/CMakeFiles/static_unac.dir/rule
.PHONY : static_unac

# fast build rule for target.
static_unac/fast:
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f port/base/unac/CMakeFiles/static_unac.dir/build.make port/base/unac/CMakeFiles/static_unac.dir/build
.PHONY : static_unac/fast

unac.o: unac.c.o
.PHONY : unac.o

# target to build an object file
unac.c.o:
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f port/base/unac/CMakeFiles/unac.dir/build.make port/base/unac/CMakeFiles/unac.dir/unac.c.o
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f port/base/unac/CMakeFiles/static_unac.dir/build.make port/base/unac/CMakeFiles/static_unac.dir/unac.c.o
.PHONY : unac.c.o

unac.i: unac.c.i
.PHONY : unac.i

# target to preprocess a source file
unac.c.i:
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f port/base/unac/CMakeFiles/unac.dir/build.make port/base/unac/CMakeFiles/unac.dir/unac.c.i
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f port/base/unac/CMakeFiles/static_unac.dir/build.make port/base/unac/CMakeFiles/static_unac.dir/unac.c.i
.PHONY : unac.c.i

unac.s: unac.c.s
.PHONY : unac.s

# target to generate assembly for a file
unac.c.s:
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f port/base/unac/CMakeFiles/unac.dir/build.make port/base/unac/CMakeFiles/unac.dir/unac.c.s
	cd /home/camilo/cmake/integration && $(MAKE) $(MAKESILENT) -f port/base/unac/CMakeFiles/static_unac.dir/build.make port/base/unac/CMakeFiles/static_unac.dir/unac.c.s
.PHONY : unac.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... static_unac"
	@echo "... unac"
	@echo "... unac.o"
	@echo "... unac.i"
	@echo "... unac.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/camilo/cmake/integration && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

